### ISSUE TITLE
[BUG] Incorrect localized date parsing

### ISSUE THREAD

**Issue by algesten** [ShammyLevva/FTAnalyzer.Mac#10]
**Version Number problem appears in**

Version 1.3.0 (54)

**Describe the bug**

"Facts dated before birth" for dates it can't parse.

<img width="1190" alt="image" src="https://user-images.githubusercontent.com/227204/88482322-cb217900-cf60-11ea-9f15-3ae87919e194.png">

<img width="873" alt="image" src="https://user-images.githubusercontent.com/227204/88482344-ed1afb80-cf60-11ea-830c-0205cc152f9a.png">

The date is recorded in Swedish (Maj is May).

**Expected behavior**

I don't expect FTAnalyzer to be able to parse all possible international date formats. However it could spot the "1870" to at least know the date is not "dated before birth"

**Comment by ShammyLevva** [comment]
For some reason I was never alerted to this issue being raised. I’ve not added support for Swedish months at present. I’m not aware though that a Swedish month shorthand was a valid month format in GEDCOM. 

The date processing is incredibly complex as it is so it has to try to work out what each possible code is. If there is a date error it stops processing and treats it as unknown. It can’t guess that a bit of the date might be a year as there’s all sorts of nonsense that people enter that has to be factored in. Processing just a number is the hardest part so it is better to flag the error and have invalid GEDCOM dates highlighted so they can be standardised.
