### ISSUE TITLE
MacFamilyTree 10.

### ISSUE THREAD

**Issue by Plantfoot** [ShammyLevva/FTAnalyzer.Mac#12]
I have been using FTAnalyser for MacFamilyTree 9 I have upgraded to 10 now it does not work.
<img width="980" alt="Screenshot 2023-04-01 at 17 56 37" src="https://user-images.githubusercontent.com/129614850/229304291-71743422-daac-44c0-bd74-aba780e42640.png">

**Comment by ShammyLevva** [comment]
None of your dates are in a valid GEDCOM format. You must not use numeric months. There is an option to fix that though in the options but no idea if it’s in the Mac version as the Mac version is no longer supported.
