### ISSUE TITLE
Crash on clicking...

### ISSUE THREAD

**Issue by MacCollector** [ShammyLevva/FTAnalyzer.Mac#2]
When I double-click on the title row for each column, the FT crashes.

**Comment by ShammyLevva** [comment]
What version are you using? And what is the exact text of the error message. 

Please use the bug template when reporting a bug there are specific questions included so you remember to include all the info I need.

**Comment by ShammyLevva** [comment]
If this was sorting then yes I'm aware that there is an issue at present which I plan to fixed prior to v1.0.6 being released on App Store.

**Comment by ShammyLevva** [comment]
Fixed for v1.0.6.19
