### ISSUE TITLE
Extended character set partially fixed

### ISSUE THREAD

**Issue by MacCollector** [ShammyLevva/FTAnalyzer.Mac#3]
The extended Character set have since v1.0.6.0 been improved and is correctly displayed in for instance: Main Lists>Individuals>Forenames.
But it has not been correctly implemented in all columns. Forinstance is the Main Lists>Individuals>Birth Location truncated where a lot of characters have lost their identity and becoming meaningless. 
False:
Vasteras, Vastmanland, Sweden
Correct:
Västerås, Västmanland, Sweden

Thanks :-)

**Comment by ShammyLevva** [comment]
I may be completely missing the importance here but I don't see (other than the twiddly bits on some letters) what the difference is.

**Comment by ShammyLevva** [comment]
Note the new version which will be out shortly will have an option to disable conversion of diacrits.

**Comment by ShammyLevva** [comment]
BTW apologies for delay in replying I'd not turned on email notifications for this project so I'd not seen the post. Fixed now.

**Comment by MacCollector** [comment]
The twiddly bits on the TOP of the characters make them completely different characters AND meaning. 

For instance in English:
Loudspeaker is not the same as
Leadspocker, even though it looks about the same with just some twiddly bits here and there. 

For instance:
Changing Å, Ä, Ö into A, A, O makes it completely wrong and unreadable. 

Sample:
Tar = Is taking...
Tår = Toes
Tär = Wears

Bor = Lives
Bör = Should

Completely different words, with just minor differences in the characters look. 


Please do not ignore all the vital characters, just because they are not in the English language. 

Best Regards

Claes Nordholm

Skickat från min iPhone....

Tfn: +46-70-3476338 [mobil]
Tfn: +46-8-54086366 [privat]

E-post:
claes.nordholm@xyleminc.com [arbete]
claes.nordholm@tele2.se [privat]
