### ISSUE TITLE
1.0.6.18 on Mac damaged

### ISSUE THREAD

**Issue by janiej** [ShammyLevva/FTAnalyzer.Mac#4]
Just tried to open BETA Test version 1.0.6.18 on Mac and it says it is damaged and needs to be sent to trash. I am able to use 1.0.6.0. I have tried to upgrade with 1.0.6.0 installed and also having deleted it first but still get the same message with 1.0.6.18. I have also downloaded it several times but the same thing happens

**Comment by ShammyLevva** [comment]
Yes this was a bad upload new version v1.0.6.19 has been tested and working.
