### ISSUE TITLE
1.0.6.19 some preferences crashing

### ISSUE THREAD

**Issue by janiej** [ShammyLevva/FTAnalyzer.Mac#6]
**Version Number problem appears in**
You MUST provide this information so I know what the scope of the problem is. Bugs without this info are unlikely to be addressed. 
NB. at no time ever in the history of the app has there been a version called “latest” they all have a version number. Such as v1.0.6.18

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by janiej** [comment]
I just downloaded 1.0.6.19 and tried Preferences. The first screen opens and can be changed but clicking on Census Settings, File Handling and Non-Gedcom dates crashes the program instead of changing to the appropriate screens

**Comment by ShammyLevva** [comment]
Fixed in v1.0.6.20 out soon.
