### ISSUE TITLE
[BUG] Problems with Research Suggestions reports

### ISSUE THREAD

**Issue by connachers** [ShammyLevva/FTAnalyzer.Mac#9]
Currently using a Mac (10.11.6) with v1.3.0 (build 54) of FTAnalyzer
**Describe the bug**
I am having a issue with the Research Suggestion tab.
When I view birth/marriage/death report, it displays but when I attempt to move cursor to the window it disappears. Also unable to print.  Similar behavior with UK & US census report.  
Irish and Canadian census reports appear to not disappear/abort, but can print. 
None of the pages are responsive to double clicking

**To Reproduce**
1. Go to 'Research Suggestions"
2. Click on 'View Colour Birth/Marriage/Death/Report'
3. BMD Window opens but will unexpectidly close.  Also when I attempt to print, no print window opens (as it does when printing 'View Irish Colour Census Report') Also for all reports cannot double click to search

Suspect data sensitivity. Sometimes the window stays open long enough I can scroll down and then sometimes the report looks fine, other times it has malformed output (see attached)

**Expected behavior**
Window remain open.  Allow double click to search.  Can print window.

**Comment by connachers** [comment]
Confirmed at least some of my issue is data related.  Created a small gedcom (5 people) and reports work (are stable and can be scrolled, also double click to search now works for me)
Although I still cannot print BMD Research Suggestion Window
.
Any suggestions on how do I troubleshoot gedcom data to find offending record(s)? 
(no errors found in Gedcom Stats although I see I have incorrect root person but am unable to figure out on mac how to change in your app)

**Comment by ShammyLevva** [comment]
Mac version no longer supported
